### ISSUE TITLE
5 second EEPROM writes will cause write exhaustion in under 200 hours

### ISSUE THREAD

**Issue by mon** [JyeSmith/18650-Backpack#1]
Logic: 100k writes / writes per hour
Writes per hour = (60/5)*60

Either slow the rate, or do some load balancing (change EEPROM address every 100k writes?) since it's 100k per cell, not for the entire flash.

**Comment by JyeSmith** [comment]
Youre not wrong!  Ive added an external eeprom (at24c02) to the pcb but Im yet to test is there is enough memory for the exteeprom lib.  Things to do...

![image](https://user-images.githubusercontent.com/14170229/52531135-84d05e00-2d5c-11e9-94cb-7fb808580312.png)

**Comment by mon** [comment]
Great to hear it! Sounds like it'll (probably) be sorted then :)

**Comment by JyeSmith** [comment]
Thanks for having a good enough look to pick that up!

If you see anywhere code can be optimised for space let me know, or submit a pull.  My next step is to cut back the font sone more.

**Comment by mon** [comment]
The 2 major things are gonna be the Arduino backend and the font. Might be more trouble than it's worth.

**Comment by JyeSmith** [comment]
External eeprom added :)

https://github.com/JyeSmith/18650-Backpack/commit/c09f394be49028447418069dc1ab59f5c57f5c23
